# Generated by Django 5.0.6 on 2024-07-14 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='user',
        ),
    ]
